name: bnext
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^7.9.2
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter_bloc: ^8.1.4
  flutter_carousel_widget: ^2.2.0
  gap: ^3.0.1
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  flutter:
    sdk: flutter
  pretty_dio_logger: ^1.4.0
  form_validator: ^2.1.1
  build_runner: ^2.4.11
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1 
  badges: ^3.1.2
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  fl_chart: ^0.69.0
  smooth_page_indicator: ^1.2.0+3
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  get_storage: ^2.1.1
  bloc: ^8.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  webview_flutter: ^4.0.1
  url_launcher: ^6.3.1
  flutter_fortune_wheel: ^1.3.2
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  path_provider: ^2.1.5
  google_generative_ai: ^0.4.7
  provider: ^6.1.5
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true
  assets:    
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf    
        - asset: assets/fonts/Poppins-BoldItalic.ttf    
        - asset: assets/fonts/Poppins-ExtraBold.ttf    
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf    
        - asset: assets/fonts/Poppins-ExtraLight.ttf    
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf    
        - asset: assets/fonts/Poppins-Medium.ttf    
        - asset: assets/fonts/Poppins-MediumItalic.ttf    
        - asset: assets/fonts/Poppins-Regular.ttf    
        - asset: assets/fonts/Poppins-SemiBold.ttf    
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf    