// c:\Users\USER\Documents\raihan\kerjaan\bnext-apps\lib\feature\shared\presentation\main.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'widget/widget.dart';
export 'main_page.dart';