// c:\Users\USER\Documents\raihan\kerjaan\bnext-apps\lib\feature\shared\presentation\main\widget.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'navbar_item.dart';