// c:\Users\USER\Documents\raihan\kerjaan\bnext-apps\lib\feature\shared\domain.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'entities/entities.dart';
