// c:\Users\USER\Documents\raihan\kerjaan\bnext-apps\lib\feature\shared\domain\repositories.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'user_repository.dart';